name: nix flake check

on:
  workflow_dispatch:
  push:
    paths:
      - "common/**.py"
      - "docs/**"
      - "**.nix"
      - "**.lock"
      - ".github/workflows/docs.yaml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix build -L .#docs
