name: nox

on:
  workflow_dispatch:
  push:
    paths:
      - "client/**.py"
      - "common/**.py"
      - "server/**.py"
      - "setup.py"
      - "nox.py"
      - ".github/workflows/nox.yml"

jobs:
  ci:
    strategy:
      matrix:
        python: [ '3.10', '3.11', '3.12' ]
        os: [ ubuntu, windows ]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest

    name: Nox - py ${{ matrix.python }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'
      - name: Install nox
        run: pip install nox
      - name: Run nox format
        run: nox -s format
      - name: Run nox test
        run: nox -s test
